apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace : {{ .Values.namespace }}
spec:
  selector:
    {{- range $key,$value := .Values.selector_labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  ports:
  {{- with .Values.service }}
    - name: http
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  type: {{ .type | default "ClusterIP" }}
  {{- end }}
